# Generated by Django 5.2.17 on 2026-08-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('icon', models.CharField(choices=[('scissors', 'Scissors (Hair)'), ('sparkles', 'Sparkles (Makeup)'), ('heart', 'Heart (Facials)'), ('award', 'Award (Nails)'), ('leaf', 'Leaf (Organic)'), ('calendar', 'Calendar (Packages)'), ('star', 'Star'), ('gem', 'Gem')], default='sparkles', max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
