# Generated by Django 5.2.17 on 2026-08-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('site_name', models.CharField(default='Luxe Beauty Salon', max_length=100)),
                ('hero_badge_text', models.CharField(default='Premium beauty services', max_length=100)),
                ('hero_heading_normal', models.CharField(default='Look your best,', max_length=150)),
                ('hero_heading_highlight', models.CharField(default='feel your best', max_length=150)),
                ('hero_description', models.TextField(default='Where elegance meets effortless beauty. Experience personalised hair, makeup and skin care in a calm, luxurious space.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('hero_rating_text', models.CharField(default='Rated 4.9/5', max_length=50)),
                ('hero_rating_subtext', models.CharField(default='by 500+ happy clients', max_length=100)),
                ('feature_badge_1', models.CharField(default='Certified stylists', max_length=100)),
                ('feature_badge_2', models.CharField(default='Organic products', max_length=100)),
                ('feature_badge_3', models.CharField(default='Walk-ins welcome', max_length=100)),
                ('phone_number', models.CharField(default='+919876543210', max_length=20)),
                ('whatsapp_number', models.CharField(default='919876543210', max_length=20)),
                ('email', models.EmailField(default='info@luxebeautysalon.com', max_length=254)),
                ('address', models.TextField(blank=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed iframe src URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
    ]
