# Generated by Django 5.2.17 on 2026-08-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. "8+", "5k+", "100%"', max_length=20)),
                ('label', models.CharField(help_text='e.g. "Years of experience"', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_button_text',
            field=models.CharField(default='Get in touch', max_length=50),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_heading_highlight',
            field=models.CharField(default='you', max_length=100),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_heading_normal',
            field=models.CharField(default='A salon built around', max_length=100),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_paragraph_1',
            field=models.TextField(default='At Luxe Beauty Salon, we believe beauty should feel effortless. Our team combines technical skill with a calming touch to create looks that fit your personality and lifestyle.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_paragraph_2',
            field=models.TextField(default='From everyday cuts to once-in-a-lifetime bridal looks, we listen first and style second. Every visit is designed to leave you refreshed, confident and glowing.'),
        ),
    ]
