# Generated by Django 5.2.17 on 2026-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_aboutstat_sitecontent_about_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('award', 'Award (Certified)'), ('leaf', 'Leaf (Premium/Organic)'), ('clock', 'Clock (On-time)'), ('heart', 'Heart (Personalised)'), ('sparkles', 'Sparkles'), ('shield', 'Shield'), ('star', 'Star'), ('gem', 'Gem')], default='award', max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='why_us_description',
            field=models.TextField(default='We combine expertise, premium products and genuine care to deliver an experience worth returning for.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='why_us_heading',
            field=models.CharField(default='Why clients love us', max_length=100),
        ),
    ]
