# Generated by Django 5.2.17 on 2026-08-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_whyusfeature_sitecontent_why_us_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='reviews_description',
            field=models.TextField(default='Real experiences from the people who make our salon special.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='reviews_heading',
            field=models.CharField(default='Client stories', max_length=100),
        ),
    ]
