# Generated by Django 5.2.17 on 2026-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0004_sitecontent_reviews_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='faq_description',
            field=models.TextField(default='Everything you may want to know before you visit.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='faq_heading',
            field=models.CharField(default='Quick questions', max_length=100),
        ),
    ]
