# Generated by Django 5.2.17 on 2026-08-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0005_faqitem_sitecontent_faq_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='business_hours',
            field=models.CharField(default='Mon – Sat: 10:00 AM – 8:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_description',
            field=models.TextField(default="Book your appointment through WhatsApp, call or email. We can't wait to welcome you."),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_heading',
            field=models.CharField(default='Visit us', max_length=100),
        ),
    ]
