# Generated by Django 5.2.17 on 2026-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0006_sitecontent_business_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed iframe src URL', max_length=1000),
        ),
    ]
