# Generated by Django 5.2.17 on 2026-08-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0007_alter_sitecontent_map_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter / X'), ('whatsapp', 'WhatsApp'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=30)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='footer_copyright_text',
            field=models.CharField(default='© 2026 Luxe Beauty Salon. All rights reserved.', max_length=150),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='footer_credit_text',
            field=models.CharField(blank=True, default='Made with care in Bangalore', max_length=100),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='footer_tagline',
            field=models.TextField(default='Where elegance meets effortless beauty. Hair, makeup, skin and nail care delivered by certified experts using premium and organic products.'),
        ),
    ]
